project:
  type: website

website:
  title: "385 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "Application Exercises"
        contents:
          - href: ae4.qmd
            text: AE 04 - Data Types
format:
  html:
    theme:
      light: brand
      dark:  vapor
    css: styles.css
    toc: true



